import React, { Component } from 'react';

class Contact extends Component {
    render() {
        return (
            <div className="container">
                <div className="row">
                    <h1 className="text-center">Contact Page</h1>
                    <hr />
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim, inquit, gubernator aeque peccat, si palearum navem evertit et si auri, item aeque peccat, qui parentem et qui servum iniuria verberat. Ex quo intellegitur, quoniam se ipsi omnes natura diligant, tam insipientem quam sapientem sumpturum, quae secundum naturam sint, reiecturumque contraria. Itaque homo in primis ingenuus et gravis, dignus illa familiaritate Scipionis et Laelii, Panaetius, cum ad Q. Nam quod ait sensibus ipsis iudicari voluptatem bonum esse, dolorem malum, plus tribuit sensibus, quam nobis leges permittunt, cum privatarum litium iudices sumus. Duo Reges: constructio interrete. Atqui si, ut convenire debet inter nos, est quaedam appetitio naturalis ea, quae secundum naturam sunt, appetens, eorum omnium est aliquae summa facienda. Quorum fuit haec institutio, in qua animadvertas velim quid mutandum putes nec expectes, dum ad omnia dicam, quae a te dicta sunt; Ergo nata est sententia veterum Academicorum et Peripateticorum, ut finem bonorum dicerent secundum naturam vivere, id est virtute adhibita frui primis a natura datis. Quanta autem ab illis varietas argumentorum ratione concludentium eorumque cum captiosis interrogationibus dissimilitudo! Quid, quod plurimis locis quasi denuntiant, ut neque sensuum fidem sine ratione nec rationis sensibus exquiramus? An ne hoc quidem Peripateticis concedis, ut dicant omnium bonorum virorum, id est sapientium omnibusque virtutibus ornatorum, vitam omnibus partibus plus habere semper boni quam mali?

                        Quaeque de virtutibus dicta sunt, quem ad modum eae semper voluptatibus inhaererent, eadem de amicitia dicenda sunt. Nec vero ut voluptatem expetat, natura movet infantem, sed tantum ut se ipse diligat, ut integrum se salvumque velit. Quod nisi ita efficitur, quae Theophrastus de fortuna, de dolore, de cruciatu corporis dixit, cum quibus coniungi vitam beatam nullo modo posse putavit, vereor, ne vera sint. Habes undique expletam et perfectam, Torquate, formam honestatis, quae tota quattuor his virtutibus, quae a te quoque commemoratae sunt, continetur. Et quidem iure fortasse, sed tamen non gravissimum est testimonium multitudinis. Quae quidem adhuc peregrinari Romae videbatur nec offerre sese nostris sermonibus, et ista maxime propter limatam quandam et rerum et verborum tenuitatem.

                        Ut vero conservetur omnis homini erga hominem societas, coniunctio, caritas, et emolumenta et detrimenta, quae felmata et blammata appellant, communia esse voluerunt; Istam voluptatem, inquit, Epicurus ignorat? Sin eam, quam Hieronymus, ne fecisset idem, ut voluptatem illam Aristippi in prima commendatione poneret. Quare si potest esse beatus is, qui est in asperis reiciendisque rebus, potest is quoque esse. Ut enim nos ex annalium monimentis testes excitamus eos, quorum omnis vita consumpta est in laboribus gloriosis, qui voluptatis nomen audire non possent, sic in vestris disputationibus historia muta est. Nihilo beatiorem esse Metellum quam Regulum. Hic cum uterque me intueretur seseque ad audiendum significarent paratos, Primum, inquam, deprecor, ne me tamquam philosophum putetis scholam vobis aliquam explicaturum, quod ne in ipsis quidem philosophis magnopere umquam probavi. Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Incommoda autem et commoda-ita enim estmata et dustmata appello-communia esse voluerunt, paria noluerunt. Illi igitur antiqui non tam acute optabiliorem illam vitam putant, praestantiorem, beatiorem, Stoici autem tantum modo praeponendam in seligendo, non quo beatior ea vita sit, sed quod ad naturam accommodatior.

                        Chrysippus autem exponens differentias animantium ait alias earum corpore excellere, alias autem animo, non nullas valere utraque re; Sin autem voluptatem putat adiungendam eam, quae sit in motu-sic enim appellat hanc dulcem: in motu, illam nihil dolentis in stabilitate-, quid tendit? Atque hoc dabitis, ut opinor, si modo sit aliquid esse beatum, id oportere totum poni in potestate sapientis. Quocirca intellegi necesse est in ipsis rebus, quae discuntur et cognoscuntur, invitamenta inesse, quibus ad discendum cognoscendumque moveamur. Non metuet autem, sive celare poterit, sive opibus magnis quicquid fecerit optinere, certeque malet existimari bonus vir, ut non sit, quam esse, ut non putetur. Quo studio cum satiari non possint, omnium ceterarum rerum obliti níhil abiectum, nihil humile cogitant; Nam voluptatis causa facere omnia, cum, etiamsi nihil consequamur, tamen ipsum illud consilium ita faciendi per se expetendum et honestum et solum bonum sit, nemo dixit. Quae est enim, quae se umquam deserat aut partem aliquam sui aut eius partis habitum aut vini aut ullius earum rerum, quae secundum naturam sunt, aut motum aut statum? Quod non subducta utilitatis ratione effici solet, sed ipsum a se oritur et sua sponte nascitur. Quamquam ego non quaero, quid tibi a me probatum sit, sed huic Ciceroni nostro, quem discipulum cupio a te abducere. Effluit igitur voluptas corporis et prima quaeque avolat saepiusque relinquit causam paenitendi quam recordandi. Cum efficere non possit ut cuiquam, qui ipse sibi notus sit, hoc est qui suam naturam sensumque perspexerit, vacuitas doloris et voluptas idem esse videatur. Rem videlicet difficilem et obscuram! individua cum dicitis et intermundia, quae nec sunt ulla nec possunt esse, intellegimus, voluptas, quae passeribus omnibus nota est, a nobis intellegi non potest? Si ad corpus pertinentibus, rationes tuas te video compensare cum istis doloribus, non memoriam corpore perceptarum voluptatum;

                    </p>
                </div>

            </div>
        );
    }
}

export default Contact;